// AI image generation → Supabase Storage upload.
// Used by the image_generation block and any "Generate image" affordance
// in the editor. Returns a public URL the block stores in props.src.
import { supabase } from "@/integrations/supabase/client";
import { ai } from "@/lib/ai-gateway";

export type GeneratedImage = {
  url: string;       // public URL in `assets` bucket
  path: string;      // storage path
  prompt: string;
  width?: number;
  height?: number;
};

/** Generate a PNG via the AI gateway, persist it, return the public URL. */
export async function generateAndUploadImage(
  prompt: string,
  opts?: { width?: number; height?: number; alt?: string },
): Promise<GeneratedImage> {
  if (!prompt.trim()) throw new Error("Prompt is required");

  const { data: u } = await supabase.auth.getUser();
  if (!u.user) throw new Error("Not signed in");

  // 1. Generate
  const { result } = await ai.image(prompt, { width: opts?.width, height: opts?.height });
  if (!result?.url) throw new Error("Image generation returned no URL");

  // 2. Fetch the generated bytes (may be a data: URL or remote URL)
  const res = await fetch(result.url);
  if (!res.ok) throw new Error(`Failed to fetch generated image (${res.status})`);
  const blob = await res.blob();
  const contentType = blob.type || "image/png";
  const ext = contentType.includes("jpeg") ? "jpg" : contentType.split("/")[1] || "png";

  // 3. Upload to `assets` bucket
  const path = `${u.user.id}/ai/${crypto.randomUUID()}.${ext}`;
  const { error: upErr } = await supabase.storage
    .from("assets")
    .upload(path, blob, { contentType, upsert: false });
  if (upErr) throw upErr;
  const { data: pub } = supabase.storage.from("assets").getPublicUrl(path);

  // 4. Register in `assets` table so it shows up in the asset picker
  try {
    await supabase.from("assets").insert({
      user_id: u.user.id,
      url: pub.publicUrl,
      path,
      name: `AI · ${prompt.slice(0, 40)}`,
      type: contentType,
      size: blob.size,
      ...(opts?.alt ? { alt: opts.alt } : {}),
    } as any);
  } catch { /* non-fatal */ }

  return { url: pub.publicUrl, path, prompt, width: opts?.width, height: opts?.height };
}
