// Brand kit ZIP packager. Browser-only (uses canvas API).
import JSZip from "jszip";
import type { PaletteSet } from "./palette";
import { paletteToCss, paletteToTailwind, paletteToScss } from "./palette";
import type { FontPairing } from "./fonts";
import { fontsCss, typographyCss } from "./fonts";
import { generateLogoSvg, svgToPng, buildIco, buildOgImage, type LogoVariant } from "./logo";
import { buildBrandGuide } from "./guide";

export type BrandKitInput = {
  brand: string;
  industry?: string;
  style?: string;
  variant: LogoVariant;
  paletteSet: PaletteSet;
  font: FontPairing;
};

export async function buildBrandKitZip(input: BrandKitInput): Promise<Blob> {
  const { brand, industry, style, variant, paletteSet, font } = input;
  const zip = new JSZip();

  const baseLogoArgs = { brand, industry, style, variant, palette: paletteSet.light, font: `"${font.display.family}", system-ui, sans-serif` };
  const logoSvg = generateLogoSvg({ ...baseLogoArgs, kind: "combination" }, 256);
  const logoDarkSvg = generateLogoSvg({ ...baseLogoArgs, palette: paletteSet.dark, kind: "combination" }, 256);
  const iconSvg = generateLogoSvg({ ...baseLogoArgs, kind: "lettermark" }, 256);
  const wordmarkSvg = generateLogoSvg({
    ...baseLogoArgs,
    palette: { ...paletteSet.light, primary: paletteSet.light.background, foreground: paletteSet.light.background },
    kind: "wordmark",
  }, 256);

  const logoFolder = zip.folder("logo")!;
  logoFolder.file("logo.svg", logoSvg);
  logoFolder.file("logo-dark.svg", logoDarkSvg);
  logoFolder.file("logo-icon.svg", iconSvg);

  // Raster outputs.
  for (const sz of [512, 1024, 2048]) {
    logoFolder.file(`logo-${sz}.png`, await svgToPng(logoSvg, sz));
  }
  logoFolder.file("apple-touch-icon.png", await svgToPng(iconSvg, 180, paletteSet.light.background));
  logoFolder.file("favicon.ico", await buildIco(iconSvg, [32, 64], paletteSet.light.background));
  logoFolder.file("og-image.png", await buildOgImage(logoSvg, brand, paletteSet.light, `"${font.display.family}", system-ui, sans-serif`));

  const colors = zip.folder("colors")!;
  colors.file("palette.css", `${paletteToCss(paletteSet.light, ":root")}\n${paletteToCss(paletteSet.dark, ":root.dark")}\n`);
  colors.file("palette.json", JSON.stringify({ light: paletteSet.light, dark: paletteSet.dark }, null, 2));
  colors.file("tailwind.config.js", paletteToTailwind(paletteSet));
  colors.file("colors.scss", paletteToScss(paletteSet));

  const fonts = zip.folder("fonts")!;
  fonts.file("font-import.css", fontsCss(font));
  fonts.file("typography.css", typographyCss(font));

  const guides = zip.folder("guidelines")!;
  guides.file("brand-guide.html", buildBrandGuide({
    brand, industry, style, paletteSet, font, logoSvg, iconSvg, wordmarkSvg,
  }));

  zip.file("README.md", `# ${brand} Brand Kit

Generated by Sitely.

Contents
- \`logo/\` — SVG logos (combination, dark, icon), favicon, apple touch icon, OG image, raster sizes.
- \`colors/\` — palette in CSS, JSON, Tailwind, SCSS formats.
- \`fonts/\` — Google Fonts import + typographic scale.
- \`guidelines/brand-guide.html\` — open in a browser to view the full identity guide.
`);

  return await zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
