/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesSlugRouteImport } from './routes/sites.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandKitRouteImport } from './routes/_authenticated/brand-kit'
import { Route as AuthenticatedAiKeysRouteImport } from './routes/_authenticated/ai-keys'
import { Route as SitesSlugPagePathRouteImport } from './routes/sites.$slug.$pagePath'
import { Route as ApiPublicPvRouteImport } from './routes/api/public/pv'
import { Route as AuthenticatedEditorProjectIdRouteImport } from './routes/_authenticated/editor.$projectId'
import { Route as ApiPublicFormsSubmitRouteImport } from './routes/api/public/forms.submit'
import { Route as ApiPublicSitesSlugSitemap_xmlRouteImport } from './routes/api/public/sites.$slug.sitemap_xml'
import { Route as ApiPublicSitesSlugRobots_txtRouteImport } from './routes/api/public/sites.$slug.robots_txt'
import { Route as ApiPublicSitesSlugManifest_webmanifestRouteImport } from './routes/api/public/sites.$slug.manifest_webmanifest'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandKitRoute = AuthenticatedBrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiKeysRoute = AuthenticatedAiKeysRouteImport.update({
  id: '/ai-keys',
  path: '/ai-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SitesSlugPagePathRoute = SitesSlugPagePathRouteImport.update({
  id: '/$pagePath',
  path: '/$pagePath',
  getParentRoute: () => SitesSlugRoute,
} as any)
const ApiPublicPvRoute = ApiPublicPvRouteImport.update({
  id: '/api/public/pv',
  path: '/api/public/pv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorProjectIdRoute =
  AuthenticatedEditorProjectIdRouteImport.update({
    id: '/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicFormsSubmitRoute = ApiPublicFormsSubmitRouteImport.update({
  id: '/api/public/forms/submit',
  path: '/api/public/forms/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitesSlugSitemap_xmlRoute =
  ApiPublicSitesSlugSitemap_xmlRouteImport.update({
    id: '/api/public/sites/$slug/sitemap_xml',
    path: '/api/public/sites/$slug/sitemap_xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSitesSlugRobots_txtRoute =
  ApiPublicSitesSlugRobots_txtRouteImport.update({
    id: '/api/public/sites/$slug/robots_txt',
    path: '/api/public/sites/$slug/robots_txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSitesSlugManifest_webmanifestRoute =
  ApiPublicSitesSlugManifest_webmanifestRouteImport.update({
    id: '/api/public/sites/$slug/manifest_webmanifest',
    path: '/api/public/sites/$slug/manifest_webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/ai-keys': typeof AuthenticatedAiKeysRoute
  '/brand-kit': typeof AuthenticatedBrandKitRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites/$slug': typeof SitesSlugRouteWithChildren
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/api/public/pv': typeof ApiPublicPvRoute
  '/sites/$slug/$pagePath': typeof SitesSlugPagePathRoute
  '/api/public/forms/submit': typeof ApiPublicFormsSubmitRoute
  '/api/public/sites/$slug/manifest_webmanifest': typeof ApiPublicSitesSlugManifest_webmanifestRoute
  '/api/public/sites/$slug/robots_txt': typeof ApiPublicSitesSlugRobots_txtRoute
  '/api/public/sites/$slug/sitemap_xml': typeof ApiPublicSitesSlugSitemap_xmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/ai-keys': typeof AuthenticatedAiKeysRoute
  '/brand-kit': typeof AuthenticatedBrandKitRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sites/$slug': typeof SitesSlugRouteWithChildren
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/api/public/pv': typeof ApiPublicPvRoute
  '/sites/$slug/$pagePath': typeof SitesSlugPagePathRoute
  '/api/public/forms/submit': typeof ApiPublicFormsSubmitRoute
  '/api/public/sites/$slug/manifest_webmanifest': typeof ApiPublicSitesSlugManifest_webmanifestRoute
  '/api/public/sites/$slug/robots_txt': typeof ApiPublicSitesSlugRobots_txtRoute
  '/api/public/sites/$slug/sitemap_xml': typeof ApiPublicSitesSlugSitemap_xmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/ai-keys': typeof AuthenticatedAiKeysRoute
  '/_authenticated/brand-kit': typeof AuthenticatedBrandKitRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/sites/$slug': typeof SitesSlugRouteWithChildren
  '/_authenticated/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
  '/api/public/pv': typeof ApiPublicPvRoute
  '/sites/$slug/$pagePath': typeof SitesSlugPagePathRoute
  '/api/public/forms/submit': typeof ApiPublicFormsSubmitRoute
  '/api/public/sites/$slug/manifest_webmanifest': typeof ApiPublicSitesSlugManifest_webmanifestRoute
  '/api/public/sites/$slug/robots_txt': typeof ApiPublicSitesSlugRobots_txtRoute
  '/api/public/sites/$slug/sitemap_xml': typeof ApiPublicSitesSlugSitemap_xmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/templates'
    | '/ai-keys'
    | '/brand-kit'
    | '/dashboard'
    | '/focus'
    | '/settings'
    | '/sites/$slug'
    | '/editor/$projectId'
    | '/api/public/pv'
    | '/sites/$slug/$pagePath'
    | '/api/public/forms/submit'
    | '/api/public/sites/$slug/manifest_webmanifest'
    | '/api/public/sites/$slug/robots_txt'
    | '/api/public/sites/$slug/sitemap_xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/templates'
    | '/ai-keys'
    | '/brand-kit'
    | '/dashboard'
    | '/focus'
    | '/settings'
    | '/sites/$slug'
    | '/editor/$projectId'
    | '/api/public/pv'
    | '/sites/$slug/$pagePath'
    | '/api/public/forms/submit'
    | '/api/public/sites/$slug/manifest_webmanifest'
    | '/api/public/sites/$slug/robots_txt'
    | '/api/public/sites/$slug/sitemap_xml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/templates'
    | '/_authenticated/ai-keys'
    | '/_authenticated/brand-kit'
    | '/_authenticated/dashboard'
    | '/_authenticated/focus'
    | '/_authenticated/settings'
    | '/sites/$slug'
    | '/_authenticated/editor/$projectId'
    | '/api/public/pv'
    | '/sites/$slug/$pagePath'
    | '/api/public/forms/submit'
    | '/api/public/sites/$slug/manifest_webmanifest'
    | '/api/public/sites/$slug/robots_txt'
    | '/api/public/sites/$slug/sitemap_xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  SitesSlugRoute: typeof SitesSlugRouteWithChildren
  ApiPublicPvRoute: typeof ApiPublicPvRoute
  ApiPublicFormsSubmitRoute: typeof ApiPublicFormsSubmitRoute
  ApiPublicSitesSlugManifest_webmanifestRoute: typeof ApiPublicSitesSlugManifest_webmanifestRoute
  ApiPublicSitesSlugRobots_txtRoute: typeof ApiPublicSitesSlugRobots_txtRoute
  ApiPublicSitesSlugSitemap_xmlRoute: typeof ApiPublicSitesSlugSitemap_xmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brand-kit': {
      id: '/_authenticated/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof AuthenticatedBrandKitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-keys': {
      id: '/_authenticated/ai-keys'
      path: '/ai-keys'
      fullPath: '/ai-keys'
      preLoaderRoute: typeof AuthenticatedAiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/sites/$slug/$pagePath': {
      id: '/sites/$slug/$pagePath'
      path: '/$pagePath'
      fullPath: '/sites/$slug/$pagePath'
      preLoaderRoute: typeof SitesSlugPagePathRouteImport
      parentRoute: typeof SitesSlugRoute
    }
    '/api/public/pv': {
      id: '/api/public/pv'
      path: '/api/public/pv'
      fullPath: '/api/public/pv'
      preLoaderRoute: typeof ApiPublicPvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$projectId': {
      id: '/_authenticated/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof AuthenticatedEditorProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/forms/submit': {
      id: '/api/public/forms/submit'
      path: '/api/public/forms/submit'
      fullPath: '/api/public/forms/submit'
      preLoaderRoute: typeof ApiPublicFormsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sites/$slug/sitemap_xml': {
      id: '/api/public/sites/$slug/sitemap_xml'
      path: '/api/public/sites/$slug/sitemap_xml'
      fullPath: '/api/public/sites/$slug/sitemap_xml'
      preLoaderRoute: typeof ApiPublicSitesSlugSitemap_xmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sites/$slug/robots_txt': {
      id: '/api/public/sites/$slug/robots_txt'
      path: '/api/public/sites/$slug/robots_txt'
      fullPath: '/api/public/sites/$slug/robots_txt'
      preLoaderRoute: typeof ApiPublicSitesSlugRobots_txtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sites/$slug/manifest_webmanifest': {
      id: '/api/public/sites/$slug/manifest_webmanifest'
      path: '/api/public/sites/$slug/manifest_webmanifest'
      fullPath: '/api/public/sites/$slug/manifest_webmanifest'
      preLoaderRoute: typeof ApiPublicSitesSlugManifest_webmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiKeysRoute: typeof AuthenticatedAiKeysRoute
  AuthenticatedBrandKitRoute: typeof AuthenticatedBrandKitRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedEditorProjectIdRoute: typeof AuthenticatedEditorProjectIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiKeysRoute: AuthenticatedAiKeysRoute,
  AuthenticatedBrandKitRoute: AuthenticatedBrandKitRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedEditorProjectIdRoute: AuthenticatedEditorProjectIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SitesSlugRouteChildren {
  SitesSlugPagePathRoute: typeof SitesSlugPagePathRoute
}

const SitesSlugRouteChildren: SitesSlugRouteChildren = {
  SitesSlugPagePathRoute: SitesSlugPagePathRoute,
}

const SitesSlugRouteWithChildren = SitesSlugRoute._addFileChildren(
  SitesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  SitesSlugRoute: SitesSlugRouteWithChildren,
  ApiPublicPvRoute: ApiPublicPvRoute,
  ApiPublicFormsSubmitRoute: ApiPublicFormsSubmitRoute,
  ApiPublicSitesSlugManifest_webmanifestRoute:
    ApiPublicSitesSlugManifest_webmanifestRoute,
  ApiPublicSitesSlugRobots_txtRoute: ApiPublicSitesSlugRobots_txtRoute,
  ApiPublicSitesSlugSitemap_xmlRoute: ApiPublicSitesSlugSitemap_xmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
